version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: app-mongo
    restart: unless-stopped
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME:-medData}
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-backend
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      # informa ao seu código que o host do Mongo é 'mongo'
      - MONGODB_HOST=mongo
    depends_on:
      - mongo
    # montar o código para dev com hot reload
    volumes:
      - ./:/usr/src/app

volumes:
  mongo_data:
